### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by luwes** [video-dev/can-autoplay#10]
Should there be any concerns around security?

Mozilla docs recommend not adding `data:` to your media-src CSP.
(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/media-src)

> data: Allows data: URIs to be used as a content source. This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.

**Comment by gkatsev** [comment]
I'm not that familiar with CSP, but could you allow `data:` for your own files only or only allow the URL that can-autoplay is being loaded from?
The idea is that we shouldn't require a separate request for the video/audio files because the latency for downloading them will make a huge difference in wait times.

A potential solution is to output a custom build of this lib that accepts URLs for the audio and video files.

**Comment by NicolasSiver** [comment]
All value of the library is around current implementation.
If you own your iFrame code, I don't see what issues you could have with security.

**Comment by luwes** [comment]
@gkatsev with inline base64 files that's not possible I think, it's not hosted anywhere. It's inline.
It definitely makes sense to do it like that. An extra request would make it a lot slower.
One thing that is possible seems is to add the mime type after the `data:` part.

@NicolasSiver I was wondering the same, I don't see any way to directly trigger a XSS from that.
It is totally possible to add javascript to a base64 string and execute it. There's an example in this page: https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/XSS%20injection

One of my colleagues mentioned a possible workaround would be to create a blob from the tiny files with `URL.createObjectURL()` and use that. It's worth a try I think, will let you know how it goes.

**Comment by gkatsev** [comment]
I've played around with `createObjectURL` before and it works but different browsers handle it slightly differently. Definitely a lot more intricacies trying to get it to work cross browser.

**Comment by caiogondim** [comment]
I'm having the same issue. I pushed to prod the lib yesterday and had to rollback. Our CSP policies doesn't allow base64 to be injected, but do for blob.
Without a blob implementation we can't use it here on The New York Times, since we can't allow base64 media to be injected dynamically in the website.

Will try to use the blob fork for now. Will post results here.

**Comment by caiogondim** [comment]
Just to say that the blob hack works for our use case. 💯

**Comment by caiogondim** [comment]
Guess we should at least consider an option to enable blob instead of base64 due to CSP restrictions.

**Comment by gkatsev** [comment]
an option makes sense to me

**Comment by caiogondim** [comment]
blob hack is working, but I still need `inline` option as well for Safari.
Will work on a PR for it.

**Comment by luwes** [comment]
that would be great, having the option. 

was just thinking now it would be a bit nicer to rename the inline option to `playsinline`.
to be consistent with the attribute, I know it's only a Safari thing but still it's a bit unexpected.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-playsinline
just thought I would bring it up :)

**Comment by gkatsev** [comment]
`playsinline` is in the HTML spec, at least in the WHATWG version of the spec.

**Comment by gkatsev** [comment]
Let's open a separate issue about renaming the `inline` option.

**Comment by caiogondim** [comment]
PR with @luwes code here https://github.com/video-dev/can-autoplay/pull/16

**Comment by NicolasSiver** [comment]
I disagree. Since the option is about inline playback, where `playsinline` implementation on the level of HTML Media Element. Options are for the library, not for the Video Tag.

**Comment by caiogondim** [comment]
@NicolasSiver We moved that discussion [here](https://github.com/video-dev/can-autoplay/issues/17)
