### ISSUE TITLE
iOS >= 10 - Mobile Safari

### ISSUE THREAD

**Issue by luwes** [video-dev/can-autoplay#11]
Is the muted video expected to fail on iOS?

The policy mentioned it would be allowed,
https://webkit.org/blog/6784/new-video-policies-for-ios/

Will do some more searching on this too.

Edit: It seems muted autoplay is possible with the `playsinline` attribute.
jsfiddle: http://jsfiddle.net/luwes/kb5s9tuh/9/

![36120671-f1a3d110-1011-11e8-9632-b22482dafbb8](https://user-images.githubusercontent.com/360826/36130938-4f0180d4-103d-11e8-9177-1fa640ccf4c1.png)

**Comment by NicolasSiver** [comment]
Apple never was really consistent with auto-play rules.
Mostly you should not rely a lot on auto-play behavior in mobile environments.

**Comment by luwes** [comment]
Yup, I agree most of the times autoplay on mobile is not needed though I do see the benefit in the library supporting the most common cases. I think for iOS>=10 the video will autoplay consistently with `muted` and `playsinline` attributes set.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-playsinline

Some examples:
http://jsfiddle.net/luwes/kb5s9tuh/9/
https://codepen.io/hay/pen/xERaVB
https://blog.synq.fm/html5-video-looping-autoplay-on-ios-and-android

I'll add the `playsinline` option in our fork, let me know if you want to add it here as well.

cc @fisherinnovation

**Comment by NicolasSiver** [comment]
`playsinline` is a part of an implementation.
Or you building a native video player playback or you are doing inline playback if you rely on your own UI.
I think we could provide `inline` property if you are interested to check mobile inline capabilities.
