### ISSUE TITLE
RFC rename `inline` option to `playsinline`

### ISSUE THREAD

**Issue by caiogondim** [video-dev/can-autoplay#17]
Discussion started [here](https://github.com/video-dev/can-autoplay/issues/10#issuecomment-366032346)

**Comment by luwes** [comment]
@NicolasSiver not fully seeing that, `playsinline` is about inline playback too. it almost says it, play(s) inline 🙂

**Comment by NicolasSiver** [comment]
`playsinline` is part of HTML Media Element implementation. There is no reason for the library to replicate HTML Media Element for some options. And it will not be a requirement for any library.

Every video engineer knows what is inline playback, so every video engineer there is no difference really between `inline` or explicit attribute `playsinline`. And I'm voting for shorter form with has good enough verbose form - `inline` than a `playsInline`. Where `inline` API says that we are going validate auto-play capabilities of an environment for inline playback. And overall it is not good enough name for an option, `Video Tag plays inline`, where `Can Autoplay library detects if auto-play is possible`.

**Comment by luwes** [comment]
Cool. Hope they don't confuse it with `video.webkitPresentationMode`.

**Comment by luwes** [comment]
Can be closed I think. Can't do myself.
