### ISSUE TITLE
Base64 vs Blob

### ISSUE THREAD

**Issue by NicolasSiver** [video-dev/can-autoplay#18]
I hardly see a value in Base64 implementation where Blob implementation works for the majority of library users, and so far nobody discovered real weaknesses of Blob approach.

I propose to do a research and comparison Base64 vs Blob. If we will find out that Blob has only good parts, we should optimize and tune library inner logic around Blob implementation. The idea to have internal regular expressions is not good enough for a small and efficient library.

When I saw a proposal/request for Blob, my instant thoughts were:

- What is a performance (detection time) difference?
- How could `Blob` be done on build step? So we don't need waste time at runtime.
- What pitfalls with Blob other than overall legacy browser support.

**Comment by NicolasSiver** [comment]
@luwes did you try chunks smaller than 1024? Any performance difference?

**Comment by luwes** [comment]
I haven't tried different size chunks. Looks it's not needed anymore :) Precompiled now, nice!
