### ISSUE TITLE
Feature request : allow to pass html video element in options

### ISSUE THREAD

**Issue by kslimani** [video-dev/can-autoplay#22]
Currently, the library [creates a video element](https://github.com/video-dev/can-autoplay/blob/master/lib/index.js#L58) to perform play using blob source.

It would be nice to be able to pass an already created video element in options object (_and create element as default behaviour if no element provided_).

The use case if for video player which "recycle" video element to load another media without changing page. (as soon as video is played is the result of user interaction, the video element keep the user consent and can be reused). This technique is used, for example, in [Clappr](https://github.com/clappr/clappr) video player.

**Comment by NicolasSiver** [comment]
Web browsers move to the implementation where as a viewer you need to bless _the page_. It means every video tag on the page will be "blessed" for the auto-play. Did you find the compromising use cases (Browser, Environment)?

**Comment by kslimani** [comment]
Oh, i think i may have missed that "page consent" feature. I did not perform tests with multiple video elements. I am gonna performs more deeper tests and comes back (and eventually closes this issue !)

**Comment by kslimani** [comment]
@NicolasSiver you are right, after user interacts with first video element, any other created video elements are allowed to autoplay on page.

Thank you, i close the issue.
