### ISSUE TITLE
Problem import

### ISSUE THREAD

**Issue by amiznikov** [video-dev/can-autoplay#23]
Hello, thanks a lot for this project, i have problem, after npm install i imorted can-autoplay like this:
import canAutoPlay from 'can-autoplay';
and browser console show me this:
Uncaught ReferenceError: canAutoplay is not defined
why is it happen?
10x!)

**Comment by amiznikov** [comment]
omg, thanks a lot, i use this example
canAutoplay.video().then(({result}) => {
  if (result === true) {
    // Can autoplay
  } else {
    // Can not autoplay
  }
})
sorry!

**Comment by NicolasSiver** [comment]
It's okay ;)
