### ISSUE TITLE
Support for below ES6

### ISSUE THREAD

**Issue by ldayananda** [video-dev/can-autoplay#7]
Thanks for starting this project!

I tried this out today and had some trouble using `uglify` as the code is in ES6. Any chance we could add a build step to use `babel` or something similar to transform the code to ES5?

**Comment by NicolasSiver** [comment]
NPM package with `main` + `module` fields?

**Comment by gkatsev** [comment]
main and module is a good idea. Though, the amount the ES6 features used and the fact there aren't any dependencies I'm not sure it's the complexity and maybe just easier to build a single es5 file since it'll work anywhere.

**Comment by NicolasSiver** [comment]
Should be resolved by #8 PR

**Comment by NicolasSiver** [comment]
The library will be deployed to NPM very soon.
